select
    segment,
    institution,
    fall_enrolled_at_year,
    student_count,
    female_count,
    round(female_count/student_count, 2) as female_percentage,
    male_count,
    round(male_count/student_count, 2) as male_percentage,
    unknown_gender_count,
    round(unknown_gender_count/student_count, 2) as unknown_gender_percentage,
    american_indian_count,
    round(american_indian_count/student_count, 2) as american_indian_percentage,
    asian_pacific_count,
    round(asian_pacific_count/student_count, 2) as asian_pacific_percentage,
    african_american_count,
    round(african_american_count/student_count, 2) as african_american_percentage,
    hispanic_latino_count,
    round(hispanic_latino_count/student_count, 2) as hispanic_latino_percentage,
    us_non_resident_count,
    round(us_non_resident_count/student_count, 2) as us_non_resident_percentage,
    multi_race_count,
    round(multi_race_count/student_count, 2) as multi_race_percentage,
    unknown_race_count,
    round(unknown_race_count/student_count, 2) as unknown_race_percentage,
    white_count,
    round(white_count/student_count, 2) as white_percentage
from {{ ref('public_postsecondary_enrollment_int') }}